//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixtureFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class StadiumInfo
    {
        public int Id { get; set; }
        public string StadiumName { get; set; }
        public string TeamName { get; set; }
        public string StadiumCapacity { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string TeamNickName { get; set; }
        public string StadiumPicture { get; set; }
        public string StadiumDescription { get; set; }
        public string ClubCrest { get; set; }
        public string Address { get; set; }
        public string TicketOffice { get; set; }
        public string WebAddress { get; set; }
    }
}
