// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FixtureFinder.Models
{

    internal class PremierLeague
    {

        [JsonProperty("count")]
        public int Count { get; set; }

        [JsonProperty("fixtures")]
        public Fixture[] Fixtures { get; set; }
    }

}
